name: "Hello Fucker"
description: "Greet Your Daddy"
author: "octocat@github.com"

inputs:
  MY_NAME: Nigbro
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
